name: Update Calendar
on:
  schedule:
    - cron: '0 0 * * *' # Обновлять ежедневно
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate calendar
        uses: athul/waka-readme@master
        with:
          SHOW_TITLE: false
          SHOW_TIME: "true"
          TIME_RANGE: "last_30_days"
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update calendar" || echo "No changes to commit"
          git push